# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "ksriadmin"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ksri-admin"
region = "ap-south-1"
image_repositories = []
disable_rollback = true
stack_name = "ksri-admin"
parameter_overrides = "Prefix=\"ksri\" UserPoolDomain=\"ksri\" useCustomDomainForUi=\"false\" UiCustomDomain=\"\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
stack_name = "ksri-admin"
resolve_s3 = true
s3_prefix = "ksri-admin"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Prefix=\"ksri\" UserPoolDomain=\"ksri\" useCustomDomainForUi=\"true\" UiCustomDomain=\"https://admin.ksri.in/\""
image_repositories = []


[prod.deploy.parameters]
stack_name = "ksri-admin"
resolve_s3 = true
s3_prefix = "ksri-admin"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Prefix=\"ksri\" UserPoolDomain=\"ksri\" useCustomDomainForUi=\"true\" UiCustomDomain=\"https://admin.ksri.in/\""
image_repositories = []
